  name: Test and Coverage

  on:
    push:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          maven: ['3.8.5']
          java: ['21']
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3  # Updated from v1 to v3

        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: ${{ matrix.java }}

        - name: Cache Maven dependencies
          uses: actions/cache@v3  # Updated to v3
          with:
            path: ~/.m2/repository
            key: maven-${{ runner.os }}-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              maven-${{ runner.os }}-${{ matrix.java }}-

        - name: Setup Maven
          uses: s4u/setup-maven-action@v1.18.0
          with:
            java-version: ${{ matrix.java }}
            maven-version: ${{ matrix.maven }}

        - name: Extract branch name
          id: extract_branch
          run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        - name: Generate test
          id: test
          run: |
            echo "compiling"
            mvn compile
            echo "testing"
            mvn test
